version: '3.8'

services:
  api:
    build: .
    container_name: securoserv
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped 